config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  root to: 'questions#index'

  resources :questions
  resources :results, only: [:new, :create, :index]
  resources :users, only: [:new, :create]
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  has_one :result

  validates :body, presence: true
  validates :points, presence: true

  def question_body
    question.body
  end

  def correct_answer
    question.answers.each do |answer|
      return answer if answer.is_correct
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers

  validates :body, presence: true
end

app/models/result.rb
# frozen_string_literal: true

class Result < ApplicationRecord
  belongs_to :user
  belongs_to :answer

  delegate :points, to: :answer, prefix: true
  delegate :is_correct, to: :answer, prefix: true
  delegate :correct_answer, to: :answer
  delegate :body, to: :answer, prefix: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # New comment
  # Another comment
  has_many :result
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login user
    session[:user_id] = user.id
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index; end

  def show
    @question = Question.find(params[:id])
    @previous = Question.where('id < ?', params[:id]).order(:id).last
    @next = Question.where('id > ?', params[:id]).order(:id).first
  end
end

app/controllers/results_controller.rb
# frozen_string_literal: true

class ResultsController < ApplicationController
  def index
    @results = current_user.results
  end

  def new
    @result = Result.new
  end

  def create
    @result = Result.new(result_params)

    if @result.save
      if next_question_available
        redirect_to question_path(next_question)
      else
        redirect_to results_path
      end
    end
  end

  private

  def result_params
    params.require(:result).permit(:answer_id, :user_id)
  end

  def next_question_available
    next_question.present?
  end

  def next_question
    params[:result][:next_question_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login @user

      redirect_to question_path(1)
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QueAy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<div class="ui grid">
  <div class="eight wide column">
    <div class="content-left">
      <%= image_tag 'dices-over-newspaper.jpg', class: 'investment-pic' %>
    </div>
  </div>
  <div class="eight wide column">
    <div class="content-right">
      <h2 class="ui header">Proposition</h2>
      <p>In Lendahand we want to make sure our investors understand what our investment offers are, how are platform works and what the risks are. </p>
      
      <p>To this end we created a test, of which the primary function is to educate.</p>
      <br/>
      <%= button_to 'Take Questions', new_user_path, method: :get, class: 'ui primary button' %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
<div class="questions">
  <div class="ui raised very padded text container segment">
    <h2 class="ui header">Knowledge and experience in investing</h2>
    <p>Note: Unlike checking and savings accounts with banks, crowdfunding is not covered by a deposit guarantee scheme, or any other guarantee scheme.</p>

    <br>
    <strong>Questions:</strong>
    <br>

    <%= render partial: 'results/form', locals: { question: @question, next: @next } %>

    <p>
    <% if @previous %>
      <%= button_to @previous, method: :get, class: 'ui left labeled icon button' do %>
        <i class="left chevron icon"></i> Back
      <% end %>
    <% end %>
    </p>
  </div>
</div>

app/views/results/_form.html.erb
<%= form_for Result.new do |f| %>
  <div class="ui form">
    <div class="grouped fields">
      <label><%= @question.body %></label>

      <% @question.answers.each do |answer| %>
        <div class="field">
          <div class="ui radio checkbox">
            <%= f.radio_button :answer_id, answer.id %>
            <%= f.label :answer, answer.body %>
          </div>
        </div>
      <% end %>

      <%= f.hidden_field :user_id, value: current_user.id  %>
      <%= f.hidden_field :next_question_id, value: @next.id if @next %>

      <%= f.submit :Submit, class: 'ui primary button' %>
    </div>
  </div>
<% end %>

<%= javascript_tag do %>
  // Cache reference to all radio buttons
  var $radioButtons = $("input:radio");
  // Based on the radio value, change the submit button attr from or to disabled
  $radioButtons.change(function(){
    var anyRadioButtonHasValue = false;

    // Iterate through all radio buttons
    $radioButtons.each(function(){
      if(this.checked) {
        // Indicate we found a radio with a value
        anyRadioButtonHasValue = true;

        // Break out of the loop
        return false;
      }
    });

    if(anyRadioButtonHasValue) {
      // enable submit button
      $("input[type='submit']").removeAttr("disabled");
    }
    else {
      // Kind of redundant unless you somehow can clear the radio button value
      $("input[type='submit']").attr("disabled", "");
    }
  });
<% end %>

app/views/results/create.html.erb
<h1>Results#create</h1>
<p>Find me in app/views/results/create.html.erb</p>

app/views/results/index.html.erb
<table class="ui celled table">
  <thead>
    <tr>
      <th colspan='3'>Results for <%= current_user.email %></th>
    </tr>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Score</th>
      <th>Correct?</th>
    </tr>
    <tbody>
      <% @results.each do |result| %>
        <% if result.answer_is_correct %>
          <tr class='positive'>
            <td><%= result.answer.question_body %></td>
            <td><%= result.answer_body %></td>
            <td><%= result.answer_points %></td>
            <td><i class="icon checkmark"></td>
          </tr>
        <% else %>
          <tr class='negative'>
            <td><%= result.answer.question_body %></td>
            <td><%= result.answer_body %> (Correct answer = "<%= result.correct_answer.body %>")</td>
            <td><%= result.answer_points %></td>
            <td><i class="icon close"></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </thead>
</table>

app/views/users/_email_modal.html.erb
<div id="#email_modal" class="ui basic modal">
  <div class="ui icon header">
    <i class="archive icon"></i>
    Archive Old Messages
  </div>
  <div class="content">
    <p>Your inbox is getting full, would you like us to enable automatic archiving of old messages?</p>
  </div>
  <div class="actions">
    <div class="ui red basic cancel inverted button">
      <i class="remove icon"></i>
      No
    </div>
    <div class="ui green ok inverted button">
      <i class="checkmark icon"></i>
      Yes
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for User.new do |f| %>
  <div class="ui raised very padded text container segment">
    <div class="ui form">
      <div class="required field">
        <label>Email</label>
        <%= f.email_field :email, required: true, placeholder: 'Email address' %>
        <p></p>
        <%= f.submit :Submit, class: 'ui primary button' %>
      </div>
    </div>
  </div>
<% end %>